
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable All

using Adventure.Foundation.ORM.Models;

namespace Feature.EventDetailsPersonalization
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using Glass.Mapper.Sc.Configuration.Attributes;
    using Glass.Mapper.Sc.Fields;
    using global::Sitecore.Data;

    /// <summary>Controls the appearance of the inheriting template in site navigation.</summary>
    ///[RepresentsSitecoreTemplateAttribute("{671e39fe-45a0-4d0d-b159-d3d54f837b4c}", "", "Feature.EventDetailsPersonalization")]
    [SitecoreType(TemplateId = Constants.EventPersonalizationSettings.TemplateIdString)]
	[GeneratedCode("Leprechaun", "1.0.0.0")]
    public partial interface IEventPersonalizationSettings : IGlassBase
    {
        
        /// <summary>Represents the Point per visit field (3811438b-0e57-4681-97a0-bf694956e48c).</summary>
        [SitecoreField(FieldName = Constants.EventPersonalizationSettings.Fields.PointPerVisit_FieldName)]
        int PointPerVisit { get; set; }

        /// <summary>Represents the Points for profile field (e9e009a7-40cb-45b6-a941-7dd1d09707c6).</summary>
        [SitecoreField(FieldName = Constants.EventPersonalizationSettings.Fields.PointsForProfile_FieldName)]
        int PointsForProfile { get; set; }

    }

}

namespace Feature.EventDetailsPersonalization.Constants
{
    using global::Sitecore.Data;
	using System.CodeDom.Compiler;

	[GeneratedCode("Leprechaun", "1.0.0.0")]
    public struct EventPersonalizationSettings
    {
        public const string TemplateIdString = "671e39fe-45a0-4d0d-b159-d3d54f837b4c";
        public static readonly ID TemplateId = new ID(TemplateIdString);

        
        public struct Fields
        {
        public static readonly ID PointPerVisit = new ID("3811438b-0e57-4681-97a0-bf694956e48c");
        public const string PointPerVisit_FieldName = "Point per visit";

        public static readonly ID PointsForProfile = new ID("e9e009a7-40cb-45b6-a941-7dd1d09707c6");
        public const string PointsForProfile_FieldName = "Points for profile";

        }
    }
}

