---
ID: "578ffa4a-b201-4a74-a313-3656713962bd"
Parent: "4666d461-2aec-4216-8aa3-ddff2f8d41f9"
Template: "9a38ad4c-ea37-4058-9693-c4be170981ba"
Path: /sitecore/content/Components/Multi Language/Language Selector Settings
DB: master
SharedFields:
- ID: "56c743eb-3fbe-421d-a963-1007e37b9f82"
  Hint: Image file
  Value: |
    <image mediaid="{CD432081-5FB9-4886-9215-358F03B33967}" />
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210111T142716Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
- Language: "ru-RU"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210112T161507Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
