---
ID: "baecbfd3-859c-4863-98aa-0e9d3951de60"
Parent: "c2e762a9-b675-4647-aa58-6b6500ad4cf3"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/Feature/Navigation/NavigationComponentSettings/Menu Settings
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210107T151225Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
