---
ID: "02134fd7-8bd9-41ea-b77a-929456b3f91b"
Parent: "f847d1bb-af68-4477-b687-9986a3a664ed"
Template: "f847d1bb-af68-4477-b687-9986a3a664ed"
Path: /sitecore/templates/Feature/Events/FeaturedEvents/Rendering Parameters/BackgoundColor/__Standard Values
DB: master
SharedFields:
- ID: "fd4e2050-186c-4375-8b99-e8a85dd7436e"
  Hint: __Enable item fallback
  Type: Checkbox
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20201203T134122Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
