
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable All

using Adventure.Foundation.ORM.Models;

namespace Feature.Login
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using Glass.Mapper.Sc.Configuration.Attributes;
    using Glass.Mapper.Sc.Fields;
    using global::Sitecore.Data;

    /// <summary>Controls the appearance of the inheriting template in site navigation.</summary>
    ///[RepresentsSitecoreTemplateAttribute("{fd17a4d0-e9c4-49f9-89a8-060bf04753e1}", "", "Feature.Login")]
    [SitecoreType(TemplateId = Constants.LoginPage.TemplateIdString)]
	[GeneratedCode("Leprechaun", "1.0.0.0")]
    public partial interface ILoginPage : IGlassBase
    {
        
    }

}

namespace Feature.Login.Constants
{
    using global::Sitecore.Data;
	using System.CodeDom.Compiler;

	[GeneratedCode("Leprechaun", "1.0.0.0")]
    public struct LoginPage
    {
        public const string TemplateIdString = "fd17a4d0-e9c4-49f9-89a8-060bf04753e1";
        public static readonly ID TemplateId = new ID(TemplateIdString);

        
    }
}

