
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable All

using Adventure.Foundation.ORM.Models;

namespace Feature.Registration.RenderingParameters
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using Glass.Mapper.Sc.Configuration.Attributes;
    using Glass.Mapper.Sc.Fields;
    using global::Sitecore.Data;

    /// <summary>Controls the appearance of the inheriting template in site navigation.</summary>
    ///[RepresentsSitecoreTemplateAttribute("{0480802e-0a12-4516-9f63-4b073323448c}", "", "Feature.Registration")]
    [SitecoreType(TemplateId = Constants.RegistrationFormParameters.TemplateIdString)]
	[GeneratedCode("Leprechaun", "1.0.0.0")]
    public partial interface IRegistrationFormParameters : IGlassBase
    {
        
        /// <summary>Represents the ConfirmPassword field (91fe74d0-2a69-4aca-aeaf-2444a5bcaee7).</summary>
        [SitecoreField(FieldName = Constants.RegistrationFormParameters.Fields.ConfirmPassword_FieldName)]
        string ConfirmPassword { get; set; }

        /// <summary>Represents the Email field (45e4ded8-bb0f-43bb-8885-89cb5b18b9c8).</summary>
        [SitecoreField(FieldName = Constants.RegistrationFormParameters.Fields.Email_FieldName)]
        string Email { get; set; }

        /// <summary>Represents the Password field (9b24649e-ed17-4540-866e-8fc37d521318).</summary>
        [SitecoreField(FieldName = Constants.RegistrationFormParameters.Fields.Password_FieldName)]
        string Password { get; set; }

        /// <summary>Represents the UserName field (02bc535c-4ee5-47e1-969f-ef8f1ea9e20b).</summary>
        [SitecoreField(FieldName = Constants.RegistrationFormParameters.Fields.UserName_FieldName)]
        string UserName { get; set; }

    }

}

namespace Feature.Registration.RenderingParameters.Constants
{
    using global::Sitecore.Data;
	using System.CodeDom.Compiler;

	[GeneratedCode("Leprechaun", "1.0.0.0")]
    public struct RegistrationFormParameters
    {
        public const string TemplateIdString = "0480802e-0a12-4516-9f63-4b073323448c";
        public static readonly ID TemplateId = new ID(TemplateIdString);

        
        public struct Fields
        {
        public static readonly ID ConfirmPassword = new ID("91fe74d0-2a69-4aca-aeaf-2444a5bcaee7");
        public const string ConfirmPassword_FieldName = "ConfirmPassword";

        public static readonly ID Email = new ID("45e4ded8-bb0f-43bb-8885-89cb5b18b9c8");
        public const string Email_FieldName = "Email";

        public static readonly ID Password = new ID("9b24649e-ed17-4540-866e-8fc37d521318");
        public const string Password_FieldName = "Password";

        public static readonly ID UserName = new ID("02bc535c-4ee5-47e1-969f-ef8f1ea9e20b");
        public const string UserName_FieldName = "UserName";

        }
    }
}
namespace Feature.Registration
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using Glass.Mapper.Sc.Configuration.Attributes;
    using Glass.Mapper.Sc.Fields;
    using global::Sitecore.Data;

    /// <summary>Controls the appearance of the inheriting template in site navigation.</summary>
    ///[RepresentsSitecoreTemplateAttribute("{4a1a2211-216d-4e5a-a401-1d632f4221b2}", "", "Feature.Registration")]
    [SitecoreType(TemplateId = Constants.RegistrationPage.TemplateIdString)]
	[GeneratedCode("Leprechaun", "1.0.0.0")]
    public partial interface IRegistrationPage : global::Foundation.ORM.Sitecore.templates.Project.Adventure.Base.IBaseNavigation, global::Foundation.ORM.Sitecore.templates.Project.Adventure.Base.IBasePage, global::Foundation.Assets.IRenderingAssets
    {
        
        /// <summary>Represents the Confirm password field (ee07f1f7-7d0c-4dbb-9792-0d4b7ccd2746).</summary>
        [SitecoreField(FieldName = Constants.RegistrationPage.Fields.ConfirmPassword_FieldName)]
        string ConfirmPassword { get; set; }

        /// <summary>Represents the Email format message field (51739bf4-f18a-4425-ac60-e4ccbd9abae5).</summary>
        [SitecoreField(FieldName = Constants.RegistrationPage.Fields.EmailFormatMessage_FieldName)]
        string EmailFormatMessage { get; set; }

        /// <summary>Represents the Email required message field (35e624db-6b66-4de8-bb64-74dc665128c7).</summary>
        [SitecoreField(FieldName = Constants.RegistrationPage.Fields.EmailRequiredMessage_FieldName)]
        string EmailRequiredMessage { get; set; }

        /// <summary>Represents the Email sent message field (74fe7e08-681a-4c12-b6d1-c17c2d1b6453).</summary>
        [SitecoreField(FieldName = Constants.RegistrationPage.Fields.EmailSentMessage_FieldName)]
        string EmailSentMessage { get; set; }

        /// <summary>Represents the Email unique message field (89bc8fd4-6ddd-4a39-b4fb-b4b48561f2c4).</summary>
        [SitecoreField(FieldName = Constants.RegistrationPage.Fields.EmailUniqueMessage_FieldName)]
        string EmailUniqueMessage { get; set; }

        /// <summary>Represents the Password contains no lower case message field (8cb1aeb3-f4a5-4186-b843-ddd514deabbc).</summary>
        [SitecoreField(FieldName = Constants.RegistrationPage.Fields.PasswordContainsNoLowerCaseMessage_FieldName)]
        string PasswordContainsNoLowerCaseMessage { get; set; }

        /// <summary>Represents the Password contains no number message field (0395d159-d7cd-4cdf-83fd-18192d284d8f).</summary>
        [SitecoreField(FieldName = Constants.RegistrationPage.Fields.PasswordContainsNoNumberMessage_FieldName)]
        string PasswordContainsNoNumberMessage { get; set; }

        /// <summary>Represents the Password contains no special message field (74985269-77b0-43cd-af38-3ecf0320e0ae).</summary>
        [SitecoreField(FieldName = Constants.RegistrationPage.Fields.PasswordContainsNoSpecialMessage_FieldName)]
        string PasswordContainsNoSpecialMessage { get; set; }

        /// <summary>Represents the Password contains no upper case message field (7d208423-441d-45b5-8a2b-73703e10c2e9).</summary>
        [SitecoreField(FieldName = Constants.RegistrationPage.Fields.PasswordContainsNoUpperCaseMessage_FieldName)]
        string PasswordContainsNoUpperCaseMessage { get; set; }

        /// <summary>Represents the Password length message field (198b4447-fc7c-483e-9d08-0121be7007b6).</summary>
        [SitecoreField(FieldName = Constants.RegistrationPage.Fields.PasswordLengthMessage_FieldName)]
        string PasswordLengthMessage { get; set; }

        /// <summary>Represents the Password required message field (b58986a2-5b79-4682-978f-bda949062a47).</summary>
        [SitecoreField(FieldName = Constants.RegistrationPage.Fields.PasswordRequiredMessage_FieldName)]
        string PasswordRequiredMessage { get; set; }

        /// <summary>Represents the Submit button text field (7507e389-ac86-4f50-bd67-4e0f793dcda8).</summary>
        [SitecoreField(FieldName = Constants.RegistrationPage.Fields.SubmitButtonText_FieldName)]
        string SubmitButtonText { get; set; }

        /// <summary>Represents the Successful registration message field (f46baa5e-8201-4020-8d74-79869c8ab86d).</summary>
        [SitecoreField(FieldName = Constants.RegistrationPage.Fields.SuccessfulRegistrationMessage_FieldName)]
        string SuccessfulRegistrationMessage { get; set; }

        /// <summary>Represents the Unsuccessful registration message field (e77859df-ac8c-425d-ab1e-b7d084b69eeb).</summary>
        [SitecoreField(FieldName = Constants.RegistrationPage.Fields.UnsuccessfulRegistrationMessage_FieldName)]
        string UnsuccessfulRegistrationMessage { get; set; }

        /// <summary>Represents the User name is not unique message field (3de6d61b-8ca8-46a7-a383-16d5649652b8).</summary>
        [SitecoreField(FieldName = Constants.RegistrationPage.Fields.UserNameIsNotUniqueMessage_FieldName)]
        string UserNameIsNotUniqueMessage { get; set; }

        /// <summary>Represents the User name length message field (836a5e1c-d518-42be-a558-196cc3bb8921).</summary>
        [SitecoreField(FieldName = Constants.RegistrationPage.Fields.UserNameLengthMessage_FieldName)]
        string UserNameLengthMessage { get; set; }

        /// <summary>Represents the User name required message field (dd483aca-b8a2-4210-a7a5-8ba079af5d86).</summary>
        [SitecoreField(FieldName = Constants.RegistrationPage.Fields.UserNameRequiredMessage_FieldName)]
        string UserNameRequiredMessage { get; set; }

    }

}

namespace Feature.Registration.Constants
{
    using global::Sitecore.Data;
	using System.CodeDom.Compiler;

	[GeneratedCode("Leprechaun", "1.0.0.0")]
    public struct RegistrationPage
    {
        public const string TemplateIdString = "4a1a2211-216d-4e5a-a401-1d632f4221b2";
        public static readonly ID TemplateId = new ID(TemplateIdString);

        
        public struct Fields
        {
        public static readonly ID ConfirmPassword = new ID("ee07f1f7-7d0c-4dbb-9792-0d4b7ccd2746");
        public const string ConfirmPassword_FieldName = "Confirm password";

        public static readonly ID EmailFormatMessage = new ID("51739bf4-f18a-4425-ac60-e4ccbd9abae5");
        public const string EmailFormatMessage_FieldName = "Email format message";

        public static readonly ID EmailRequiredMessage = new ID("35e624db-6b66-4de8-bb64-74dc665128c7");
        public const string EmailRequiredMessage_FieldName = "Email required message";

        public static readonly ID EmailSentMessage = new ID("74fe7e08-681a-4c12-b6d1-c17c2d1b6453");
        public const string EmailSentMessage_FieldName = "Email sent message";

        public static readonly ID EmailUniqueMessage = new ID("89bc8fd4-6ddd-4a39-b4fb-b4b48561f2c4");
        public const string EmailUniqueMessage_FieldName = "Email unique message";

        public static readonly ID PasswordContainsNoLowerCaseMessage = new ID("8cb1aeb3-f4a5-4186-b843-ddd514deabbc");
        public const string PasswordContainsNoLowerCaseMessage_FieldName = "Password contains no lower case message";

        public static readonly ID PasswordContainsNoNumberMessage = new ID("0395d159-d7cd-4cdf-83fd-18192d284d8f");
        public const string PasswordContainsNoNumberMessage_FieldName = "Password contains no number message";

        public static readonly ID PasswordContainsNoSpecialMessage = new ID("74985269-77b0-43cd-af38-3ecf0320e0ae");
        public const string PasswordContainsNoSpecialMessage_FieldName = "Password contains no special message";

        public static readonly ID PasswordContainsNoUpperCaseMessage = new ID("7d208423-441d-45b5-8a2b-73703e10c2e9");
        public const string PasswordContainsNoUpperCaseMessage_FieldName = "Password contains no upper case message";

        public static readonly ID PasswordLengthMessage = new ID("198b4447-fc7c-483e-9d08-0121be7007b6");
        public const string PasswordLengthMessage_FieldName = "Password length message";

        public static readonly ID PasswordRequiredMessage = new ID("b58986a2-5b79-4682-978f-bda949062a47");
        public const string PasswordRequiredMessage_FieldName = "Password required message";

        public static readonly ID SubmitButtonText = new ID("7507e389-ac86-4f50-bd67-4e0f793dcda8");
        public const string SubmitButtonText_FieldName = "Submit button text";

        public static readonly ID SuccessfulRegistrationMessage = new ID("f46baa5e-8201-4020-8d74-79869c8ab86d");
        public const string SuccessfulRegistrationMessage_FieldName = "Successful registration message";

        public static readonly ID UnsuccessfulRegistrationMessage = new ID("e77859df-ac8c-425d-ab1e-b7d084b69eeb");
        public const string UnsuccessfulRegistrationMessage_FieldName = "Unsuccessful registration message";

        public static readonly ID UserNameIsNotUniqueMessage = new ID("3de6d61b-8ca8-46a7-a383-16d5649652b8");
        public const string UserNameIsNotUniqueMessage_FieldName = "User name is not unique message";

        public static readonly ID UserNameLengthMessage = new ID("836a5e1c-d518-42be-a558-196cc3bb8921");
        public const string UserNameLengthMessage_FieldName = "User name length message";

        public static readonly ID UserNameRequiredMessage = new ID("dd483aca-b8a2-4210-a7a5-8ba079af5d86");
        public const string UserNameRequiredMessage_FieldName = "User name required message";

        }
    }
}
namespace Feature.Registration
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using Glass.Mapper.Sc.Configuration.Attributes;
    using Glass.Mapper.Sc.Fields;
    using global::Sitecore.Data;

    /// <summary>Controls the appearance of the inheriting template in site navigation.</summary>
    ///[RepresentsSitecoreTemplateAttribute("{6ddefd97-9ccd-42b5-9849-301c42d25460}", "", "Feature.Registration")]
    [SitecoreType(TemplateId = Constants.WelcomingEmail.TemplateIdString)]
	[GeneratedCode("Leprechaun", "1.0.0.0")]
    public partial interface IWelcomingEmail : IGlassBase
    {
        
        /// <summary>Represents the Body field (7f1b1322-b2d4-4985-bfb2-297aa97fe533).</summary>
        [SitecoreField(FieldName = Constants.WelcomingEmail.Fields.Body_FieldName)]
        string Body { get; set; }

        /// <summary>Represents the Header field (3a444dce-f111-47ec-a03f-77c26537bf51).</summary>
        [SitecoreField(FieldName = Constants.WelcomingEmail.Fields.Header_FieldName)]
        string Header { get; set; }

        /// <summary>Represents the Styles field (1e6a2481-3fae-4fa3-8c16-d4409850fc9a).</summary>
        [SitecoreField(FieldName = Constants.WelcomingEmail.Fields.Styles_FieldName)]
        string Styles { get; set; }

        /// <summary>Represents the Subject field (9b98df65-5343-4c52-8d30-1def2ad83779).</summary>
        [SitecoreField(FieldName = Constants.WelcomingEmail.Fields.Subject_FieldName)]
        string Subject { get; set; }

    }

}

namespace Feature.Registration.Constants
{
    using global::Sitecore.Data;
	using System.CodeDom.Compiler;

	[GeneratedCode("Leprechaun", "1.0.0.0")]
    public struct WelcomingEmail
    {
        public const string TemplateIdString = "6ddefd97-9ccd-42b5-9849-301c42d25460";
        public static readonly ID TemplateId = new ID(TemplateIdString);

        
        public struct Fields
        {
        public static readonly ID Body = new ID("7f1b1322-b2d4-4985-bfb2-297aa97fe533");
        public const string Body_FieldName = "Body";

        public static readonly ID Header = new ID("3a444dce-f111-47ec-a03f-77c26537bf51");
        public const string Header_FieldName = "Header";

        public static readonly ID Styles = new ID("1e6a2481-3fae-4fa3-8c16-d4409850fc9a");
        public const string Styles_FieldName = "Styles";

        public static readonly ID Subject = new ID("9b98df65-5343-4c52-8d30-1def2ad83779");
        public const string Subject_FieldName = "Subject";

        }
    }
}

