
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable All

using Adventure.Foundation.ORM.Models;

namespace Feature.Navigation
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using Glass.Mapper.Sc.Configuration.Attributes;
    using Glass.Mapper.Sc.Fields;
    using global::Sitecore.Data;

    /// <summary>Controls the appearance of the inheriting template in site navigation.</summary>
    ///[RepresentsSitecoreTemplateAttribute("{c2e762a9-b675-4647-aa58-6b6500ad4cf3}", "", "Feature.Navigation")]
    [SitecoreType(TemplateId = Constants.NavigationComponentSettings.TemplateIdString)]
	[GeneratedCode("Leprechaun", "1.0.0.0")]
    public partial interface INavigationComponentSettings : IGlassBase
    {
        
        /// <summary>Represents the Title field (21e75ac1-1060-4dfd-ad66-7c2ab301ac15).</summary>
        [SitecoreField(FieldName = Constants.NavigationComponentSettings.Fields.Title_FieldName)]
        string Title { get; set; }

    }

}

namespace Feature.Navigation.Constants
{
    using global::Sitecore.Data;
	using System.CodeDom.Compiler;

	[GeneratedCode("Leprechaun", "1.0.0.0")]
    public struct NavigationComponentSettings
    {
        public const string TemplateIdString = "c2e762a9-b675-4647-aa58-6b6500ad4cf3";
        public static readonly ID TemplateId = new ID(TemplateIdString);

        
        public struct Fields
        {
        public static readonly ID Title = new ID("21e75ac1-1060-4dfd-ad66-7c2ab301ac15");
        public const string Title_FieldName = "Title";

        }
    }
}

