
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable All

using Adventure.Foundation.ORM.Models;

namespace Feature.Mailing
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using Glass.Mapper.Sc.Configuration.Attributes;
    using Glass.Mapper.Sc.Fields;
    using global::Sitecore.Data;

    /// <summary>Controls the appearance of the inheriting template in site navigation.</summary>
    ///[RepresentsSitecoreTemplateAttribute("{462bbb17-0ca9-4436-ad24-b58d3b12fa18}", "", "Feature.Mailing")]
    [SitecoreType(TemplateId = Constants.SubscriptionForm.TemplateIdString)]
	[GeneratedCode("Leprechaun", "1.0.0.0")]
    public partial interface ISubscriptionForm : IGlassBase
    {
        
        /// <summary>Represents the Email field (e0209549-2ed3-474c-9292-4cca782d2c57).</summary>
        [SitecoreField(FieldName = Constants.SubscriptionForm.Fields.Email_FieldName)]
        string Email { get; }

        /// <summary>Represents the Fail field (80814aa2-1515-4049-9b6b-2953bb29864d).</summary>
        [SitecoreField(FieldName = Constants.SubscriptionForm.Fields.Fail_FieldName)]
        string Fail { get; }

        /// <summary>Represents the Subscribe field (d3de7d1f-17e2-488c-8f44-8e5b447da015).</summary>
        [SitecoreField(FieldName = Constants.SubscriptionForm.Fields.Subscribe_FieldName)]
        string Subscribe { get; }

        /// <summary>Represents the SubscriptionEmail field (9a1d5af2-410c-40ad-aa3b-e165fa2dfd7b).</summary>
        [SitecoreField(FieldName = Constants.SubscriptionForm.Fields.SubscriptionEmail_FieldName)]
        string SubscriptionEmail { get; }

        /// <summary>Represents the Success field (50df15ad-de65-47d4-ab66-64c9d80ad8c1).</summary>
        [SitecoreField(FieldName = Constants.SubscriptionForm.Fields.Success_FieldName)]
        string Success { get; }

    }

}

namespace Feature.Mailing.Constants
{
    using global::Sitecore.Data;
	using System.CodeDom.Compiler;

	[GeneratedCode("Leprechaun", "1.0.0.0")]
    public struct SubscriptionForm
    {
        public const string TemplateIdString = "462bbb17-0ca9-4436-ad24-b58d3b12fa18";
        public static readonly ID TemplateId = new ID(TemplateIdString);

        
        public struct Fields
        {
        public static readonly ID Email = new ID("e0209549-2ed3-474c-9292-4cca782d2c57");
        public const string Email_FieldName = "Email";

        public static readonly ID Fail = new ID("80814aa2-1515-4049-9b6b-2953bb29864d");
        public const string Fail_FieldName = "Fail";

        public static readonly ID Subscribe = new ID("d3de7d1f-17e2-488c-8f44-8e5b447da015");
        public const string Subscribe_FieldName = "Subscribe";

        public static readonly ID SubscriptionEmail = new ID("9a1d5af2-410c-40ad-aa3b-e165fa2dfd7b");
        public const string SubscriptionEmail_FieldName = "SubscriptionEmail";

        public static readonly ID Success = new ID("50df15ad-de65-47d4-ab66-64c9d80ad8c1");
        public const string Success_FieldName = "Success";

        }
    }
}

