
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable All

using Adventure.Foundation.ORM.Models;

namespace Foundation.EmailProvider
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using Glass.Mapper.Sc.Configuration.Attributes;
    using Glass.Mapper.Sc.Fields;
    using global::Sitecore.Data;

    /// <summary>Controls the appearance of the inheriting template in site navigation.</summary>
    ///[RepresentsSitecoreTemplateAttribute("{451528d5-f488-4759-bae6-8a3b763c0720}", "", "Foundation.Mailing")]
    [SitecoreType(TemplateId = Constants.Email.TemplateIdString)]
	[GeneratedCode("Leprechaun", "1.0.0.0")]
    public partial interface IEmail : IGlassBase
    {
        
        /// <summary>Represents the Body field (5f477753-d010-4129-b4ab-d40b1d4a5c90).</summary>
        [SitecoreField(FieldName = Constants.Email.Fields.Body_FieldName)]
        string Body { get; set; }

        /// <summary>Represents the Header field (40554ec3-3349-4896-964e-d1715604746c).</summary>
        [SitecoreField(FieldName = Constants.Email.Fields.Header_FieldName)]
        string Header { get; set; }

        /// <summary>Represents the Styles field (da10655d-6670-4217-8e6e-e1390fbc66d9).</summary>
        [SitecoreField(FieldName = Constants.Email.Fields.Styles_FieldName)]
        string Styles { get; set; }

        /// <summary>Represents the Subject field (bb2334c1-3b1a-4c3c-bec9-6df0e6f10536).</summary>
        [SitecoreField(FieldName = Constants.Email.Fields.Subject_FieldName)]
        string Subject { get; set; }

    }

}

namespace Foundation.EmailProvider.Constants
{
    using global::Sitecore.Data;
	using System.CodeDom.Compiler;

	[GeneratedCode("Leprechaun", "1.0.0.0")]
    public struct Email
    {
        public const string TemplateIdString = "451528d5-f488-4759-bae6-8a3b763c0720";
        public static readonly ID TemplateId = new ID(TemplateIdString);

        
        public struct Fields
        {
        public static readonly ID Body = new ID("5f477753-d010-4129-b4ab-d40b1d4a5c90");
        public const string Body_FieldName = "Body";

        public static readonly ID Header = new ID("40554ec3-3349-4896-964e-d1715604746c");
        public const string Header_FieldName = "Header";

        public static readonly ID Styles = new ID("da10655d-6670-4217-8e6e-e1390fbc66d9");
        public const string Styles_FieldName = "Styles";

        public static readonly ID Subject = new ID("bb2334c1-3b1a-4c3c-bec9-6df0e6f10536");
        public const string Subject_FieldName = "Subject";

        }
    }
}

