---
ID: "4c159f58-f42e-4e78-831d-764123b18022"
Parent: "0480802e-0a12-4516-9f63-4b073323448c"
Template: "0480802e-0a12-4516-9f63-4b073323448c"
Path: /sitecore/templates/Feature/Registration/Rendering Parameters/Registration Form Parameters/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "02bc535c-4ee5-47e1-969f-ef8f1ea9e20b"
      Hint: UserName
      Value: User name
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20201125T130558Z
    - ID: "45e4ded8-bb0f-43bb-8885-89cb5b18b9c8"
      Hint: Email
      Value: Email
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "91fe74d0-2a69-4aca-aeaf-2444a5bcaee7"
      Hint: ConfirmPassword
      Value: Confirm password
    - ID: "9b24649e-ed17-4540-866e-8fc37d521318"
      Hint: Password
      Value: Password
