
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable All

using Adventure.Foundation.ORM.Models;

namespace Foundation.ORM.Sitecore.templates.Project.Adventure
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using Glass.Mapper.Sc.Configuration.Attributes;
    using Glass.Mapper.Sc.Fields;
    using global::Sitecore.Data;

    /// <summary>Controls the appearance of the inheriting template in site navigation.</summary>
    ///[RepresentsSitecoreTemplateAttribute("{72b40e48-a2b6-4ddf-be66-ad0911f53f75}", "", "Foundation.ORM")]
    [SitecoreType(TemplateId = Constants.EventDetailsPage.TemplateIdString)]
	[GeneratedCode("Leprechaun", "1.0.0.0")]
    public partial interface IEventDetailsPage : global::Foundation.ORM.Sitecore.templates.Project.Adventure.Base.IBaseNavigation
    {
        
        /// <summary>Represents the ButtonText field (3986d092-0659-41f4-9d38-072639a93098).</summary>
        [SitecoreField(FieldName = Constants.EventDetailsPage.Fields.ButtonText_FieldName)]
        string ButtonText { get; set; }

        /// <summary>Represents the Description field (a0cff737-944a-43ef-9fa8-810d54a7c876).</summary>
        [SitecoreField(FieldName = Constants.EventDetailsPage.Fields.Description_FieldName)]
        string Description { get; set; }

        /// <summary>Represents the Difficulty field (9bdeb640-bb42-456c-a7e9-6fcf76ba9f93).</summary>
        [SitecoreField(FieldName = Constants.EventDetailsPage.Fields.Difficulty_FieldName)]
        int Difficulty { get; set; }

        /// <summary>Represents the EndDate field (d0b7c6a1-7c82-4f01-9da7-48a825e667ee).</summary>
        [SitecoreField(FieldName = Constants.EventDetailsPage.Fields.EndDate_FieldName)]
        DateTime EndDate { get; set; }

        /// <summary>Represents the Image field (cef157e6-ff57-4378-8059-47faed792b7d).</summary>
        [SitecoreField(FieldName = Constants.EventDetailsPage.Fields.Image_FieldName)]
        Image Image { get; set; }

        /// <summary>Represents the ShortDescription field (7b440603-9dc7-45a4-9935-94ea995e005a).</summary>
        [SitecoreField(FieldName = Constants.EventDetailsPage.Fields.ShortDescription_FieldName)]
        string ShortDescription { get; set; }

        /// <summary>Represents the StartDate field (23a213e8-4b53-4e63-8ca6-309d0e88db5a).</summary>
        [SitecoreField(FieldName = Constants.EventDetailsPage.Fields.StartDate_FieldName)]
        DateTime StartDate { get; set; }

        /// <summary>Represents the Tags field (c1b4d955-3944-4eca-a1c3-0cdd2fdc9926).</summary>
        [SitecoreField(FieldName = Constants.EventDetailsPage.Fields.Tags_FieldName)]
        IEnumerable<IEventTag> Tags { get; set; }

        /// <summary>Represents the Title field (50911beb-2fa0-4b2f-bb02-7c014fa793f2).</summary>
        [SitecoreField(FieldName = Constants.EventDetailsPage.Fields.Title_FieldName)]
        string Title { get; set; }

    }

}

namespace Foundation.ORM.Sitecore.templates.Project.Adventure.Constants
{
    using global::Sitecore.Data;
	using System.CodeDom.Compiler;

	[GeneratedCode("Leprechaun", "1.0.0.0")]
    public struct EventDetailsPage
    {
        public const string TemplateIdString = "72b40e48-a2b6-4ddf-be66-ad0911f53f75";
        public static readonly ID TemplateId = new ID(TemplateIdString);

        
        public struct Fields
        {
        public static readonly ID ButtonText = new ID("3986d092-0659-41f4-9d38-072639a93098");
        public const string ButtonText_FieldName = "ButtonText";

        public static readonly ID Description = new ID("a0cff737-944a-43ef-9fa8-810d54a7c876");
        public const string Description_FieldName = "Description";

        public static readonly ID Difficulty = new ID("9bdeb640-bb42-456c-a7e9-6fcf76ba9f93");
        public const string Difficulty_FieldName = "Difficulty";

        public static readonly ID EndDate = new ID("d0b7c6a1-7c82-4f01-9da7-48a825e667ee");
        public const string EndDate_FieldName = "EndDate";

        public static readonly ID Image = new ID("cef157e6-ff57-4378-8059-47faed792b7d");
        public const string Image_FieldName = "Image";

        public static readonly ID ShortDescription = new ID("7b440603-9dc7-45a4-9935-94ea995e005a");
        public const string ShortDescription_FieldName = "ShortDescription";

        public static readonly ID StartDate = new ID("23a213e8-4b53-4e63-8ca6-309d0e88db5a");
        public const string StartDate_FieldName = "StartDate";

        public static readonly ID Tags = new ID("c1b4d955-3944-4eca-a1c3-0cdd2fdc9926");
        public const string Tags_FieldName = "Tags";

        public static readonly ID Title = new ID("50911beb-2fa0-4b2f-bb02-7c014fa793f2");
        public const string Title_FieldName = "Title";

        }
    }
}
namespace Foundation.ORM.Sitecore.templates.Project.Adventure
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using Glass.Mapper.Sc.Configuration.Attributes;
    using Glass.Mapper.Sc.Fields;
    using global::Sitecore.Data;

    /// <summary>Controls the appearance of the inheriting template in site navigation.</summary>
    ///[RepresentsSitecoreTemplateAttribute("{fb686a69-7ea4-462f-91ed-4610ef0ba908}", "", "Foundation.ORM")]
    [SitecoreType(TemplateId = Constants.EventListPage.TemplateIdString)]
	[GeneratedCode("Leprechaun", "1.0.0.0")]
    public partial interface IEventListPage : global::Foundation.ORM.Sitecore.templates.Project.Adventure.Base.IBaseNavigation, global::Foundation.ORM.Sitecore.templates.Project.Adventure.Base.IBasePage
    {
        
        /// <summary>Represents the Events field (e2cd9b8c-16e5-447b-bb87-b2d699fbc875).</summary>
        [SitecoreField(FieldName = Constants.EventListPage.Fields.Events_FieldName)]
        IEnumerable<IEventDetailsPage> Events { get; set; }

    }

}

namespace Foundation.ORM.Sitecore.templates.Project.Adventure.Constants
{
    using global::Sitecore.Data;
	using System.CodeDom.Compiler;

	[GeneratedCode("Leprechaun", "1.0.0.0")]
    public struct EventListPage
    {
        public const string TemplateIdString = "fb686a69-7ea4-462f-91ed-4610ef0ba908";
        public static readonly ID TemplateId = new ID(TemplateIdString);

        
        public struct Fields
        {
        public static readonly ID Events = new ID("e2cd9b8c-16e5-447b-bb87-b2d699fbc875");
        public const string Events_FieldName = "Events";

        }
    }
}
namespace Foundation.ORM.Sitecore.templates.Project.Adventure
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using Glass.Mapper.Sc.Configuration.Attributes;
    using Glass.Mapper.Sc.Fields;
    using global::Sitecore.Data;

    /// <summary>Controls the appearance of the inheriting template in site navigation.</summary>
    ///[RepresentsSitecoreTemplateAttribute("{5b506a31-71fd-412d-8944-4e6059c2461e}", "", "Foundation.ORM")]
    [SitecoreType(TemplateId = Constants.EventTag.TemplateIdString)]
	[GeneratedCode("Leprechaun", "1.0.0.0")]
    public partial interface IEventTag : IGlassBase
    {
        
        /// <summary>Represents the Tag Name field (c8ccee70-196f-4f8d-ae74-36f81ca43268).</summary>
        [SitecoreField(FieldName = Constants.EventTag.Fields.TagName_FieldName)]
        string TagName { get; set; }

    }

}

namespace Foundation.ORM.Sitecore.templates.Project.Adventure.Constants
{
    using global::Sitecore.Data;
	using System.CodeDom.Compiler;

	[GeneratedCode("Leprechaun", "1.0.0.0")]
    public struct EventTag
    {
        public const string TemplateIdString = "5b506a31-71fd-412d-8944-4e6059c2461e";
        public static readonly ID TemplateId = new ID(TemplateIdString);

        
        public struct Fields
        {
        public static readonly ID TagName = new ID("c8ccee70-196f-4f8d-ae74-36f81ca43268");
        public const string TagName_FieldName = "Tag Name";

        }
    }
}
namespace Foundation.ORM.Sitecore.templates.Project.Adventure
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using Glass.Mapper.Sc.Configuration.Attributes;
    using Glass.Mapper.Sc.Fields;
    using global::Sitecore.Data;

    /// <summary>Controls the appearance of the inheriting template in site navigation.</summary>
    ///[RepresentsSitecoreTemplateAttribute("{8117be40-deaf-444a-b90f-2000446ff085}", "", "Foundation.ORM")]
    [SitecoreType(TemplateId = Constants.HomePage.TemplateIdString)]
	[GeneratedCode("Leprechaun", "1.0.0.0")]
    public partial interface IHomePage : global::Foundation.ORM.Sitecore.templates.Project.Adventure.Base.IBaseNavigation, global::Foundation.ORM.Sitecore.templates.Project.Adventure.Base.IBasePage
    {
        
    }

}

namespace Foundation.ORM.Sitecore.templates.Project.Adventure.Constants
{
    using global::Sitecore.Data;
	using System.CodeDom.Compiler;

	[GeneratedCode("Leprechaun", "1.0.0.0")]
    public struct HomePage
    {
        public const string TemplateIdString = "8117be40-deaf-444a-b90f-2000446ff085";
        public static readonly ID TemplateId = new ID(TemplateIdString);

        
    }
}
namespace Foundation.ORM.Sitecore.templates.Project.Adventure.Base
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using Glass.Mapper.Sc.Configuration.Attributes;
    using Glass.Mapper.Sc.Fields;
    using global::Sitecore.Data;

    /// <summary>Controls the appearance of the inheriting template in site navigation.</summary>
    ///[RepresentsSitecoreTemplateAttribute("{0721b93d-9c70-4d29-bd35-fa672024ca2c}", "", "Foundation.ORM")]
    [SitecoreType(TemplateId = Constants.BaseNavigation.TemplateIdString)]
	[GeneratedCode("Leprechaun", "1.0.0.0")]
    public partial interface IBaseNavigation : IGlassBase
    {
        
        /// <summary>Represents the ExcludeFromNavigation field (d113ce03-4125-49bd-bbce-acc236d729e1).</summary>
        [SitecoreField(FieldName = Constants.BaseNavigation.Fields.ExcludeFromNavigation_FieldName)]
        bool ExcludeFromNavigation { get; set; }

    }

}

namespace Foundation.ORM.Sitecore.templates.Project.Adventure.Base.Constants
{
    using global::Sitecore.Data;
	using System.CodeDom.Compiler;

	[GeneratedCode("Leprechaun", "1.0.0.0")]
    public struct BaseNavigation
    {
        public const string TemplateIdString = "0721b93d-9c70-4d29-bd35-fa672024ca2c";
        public static readonly ID TemplateId = new ID(TemplateIdString);

        
        public struct Fields
        {
        public static readonly ID ExcludeFromNavigation = new ID("d113ce03-4125-49bd-bbce-acc236d729e1");
        public const string ExcludeFromNavigation_FieldName = "ExcludeFromNavigation";

        }
    }
}
namespace Foundation.ORM.Sitecore.templates.Project.Adventure.Base
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using Glass.Mapper.Sc.Configuration.Attributes;
    using Glass.Mapper.Sc.Fields;
    using global::Sitecore.Data;

    /// <summary>Controls the appearance of the inheriting template in site navigation.</summary>
    ///[RepresentsSitecoreTemplateAttribute("{a2e9c57c-8a98-4dde-af77-11b9dce9a293}", "", "Foundation.ORM")]
    [SitecoreType(TemplateId = Constants.BasePage.TemplateIdString)]
	[GeneratedCode("Leprechaun", "1.0.0.0")]
    public partial interface IBasePage : IGlassBase
    {
        
        /// <summary>Represents the Footer field (bdccd8d5-015d-4c2c-9580-0df03bef605c).</summary>
        [SitecoreField(FieldName = Constants.BasePage.Fields.Footer_FieldName)]
        Guid Footer { get; set; }

    }

}

namespace Foundation.ORM.Sitecore.templates.Project.Adventure.Base.Constants
{
    using global::Sitecore.Data;
	using System.CodeDom.Compiler;

	[GeneratedCode("Leprechaun", "1.0.0.0")]
    public struct BasePage
    {
        public const string TemplateIdString = "a2e9c57c-8a98-4dde-af77-11b9dce9a293";
        public static readonly ID TemplateId = new ID(TemplateIdString);

        
        public struct Fields
        {
        public static readonly ID Footer = new ID("bdccd8d5-015d-4c2c-9580-0df03bef605c");
        public const string Footer_FieldName = "Footer";

        }
    }
}

